export const ActionTypes = {
    // Revenue by Country
    FETCH_REVENUE_BY_COUNTRY_START: "FETCH_REVENUE_BY_COUNTRY_START",
    FETCH_REVENUE_BY_COUNTRY_SUCCESS: "FETCH_REVENUE_BY_COUNTRY_SUCCESS",
    FETCH_REVENUE_BY_COUNTRY_ERROR: "FETCH_REVENUE_BY_COUNTRY_ERROR",
  
    // Top Products
    FETCH_TOP_PRODUCTS_START: "FETCH_TOP_PRODUCTS_START",
    FETCH_TOP_PRODUCTS_SUCCESS: "FETCH_TOP_PRODUCTS_SUCCESS",
    FETCH_TOP_PRODUCTS_ERROR: "FETCH_TOP_PRODUCTS_ERROR",
  
    // Top Regions
    FETCH_TOP_REGIONS_START: "FETCH_TOP_REGIONS_START",
    FETCH_TOP_REGIONS_SUCCESS: "FETCH_TOP_REGIONS_SUCCESS",
    FETCH_TOP_REGIONS_ERROR: "FETCH_TOP_REGIONS_ERROR",
  
    // Monthly Sales
    FETCH_MONTHLY_SALES_START: "FETCH_MONTHLY_SALES_START",
    FETCH_MONTHLY_SALES_SUCCESS: "FETCH_MONTHLY_SALES_SUCCESS",
    FETCH_MONTHLY_SALES_ERROR: "FETCH_MONTHLY_SALES_ERROR",
  
    // Reset
    RESET_STATE: "RESET_STATE",
  } as const;